### ISSUE TITLE
No module named 'FaceRecognizer'

### ISSUE THREAD

**Issue by 623416947** [Danbinabo/insighrface#8]
作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。

**Comment by Danbinabo** [comment]
我确认一下有没有，再发你吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"623416947"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 下午4:01
收件人:&nbsp;"Danbinabo/insighrface"<insighrface@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Danbinabo/insighrface] No module named 'FaceRecognizer' (#8)





 
作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。

**Comment by DorothyYan** [comment]
请问作者大神有将FaceRecognizer.py发出来么？同志们能否发出来呢？蟹蟹

**Comment by DorothyYan** [comment]
> 作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。

请问作者发给你了吗？能不能发给我一份呢？邮箱1360090837@qq.com

**Comment by ming-asm** [comment]
> > 作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。
> 
> 请问作者发给你了吗？能不能发给我一份呢？邮箱[1360090837@qq.com](mailto:1360090837@qq.com
请问作者发你了吗？能不能也发我一份？谢谢啦～邮箱535145966@qq.com

**Comment by DorothyYan** [comment]
没有呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ming-asm"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 中午11:20
收件人: "Danbinabo/insighrface"<insighrface@noreply.github.com&gt;; 
抄送: "蓝色冰点"<1360090837@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Danbinabo/insighrface] No module named &#39;FaceRecognizer&#39; (#8)





   
作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。
  
请问作者发给你了吗？能不能发给我一份呢？邮箱[1360090837@qq.com](mailto:1360090837@qq.com
 请问作者发你了吗？能不能也发我一份？谢谢啦～邮箱535145966@qq.com

**Comment by dreamercv** [comment]
1367955240@qq.com能发我一份吗？我也没找到这个文件夹`FaceRecognizer.py`

**Comment by dreamercv** [comment]
> > > 作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。
> > 
> > 
> > 请问作者发给你了吗？能不能发给我一份呢？邮箱[[1360090837@qq.com](mailto:1360090837@qq.com)](mailto:[1360090837@qq.com](mailto:1360090837@qq.com)
> > 请问作者发你了吗？能不能也发我一份？谢谢啦～邮箱[535145966@qq.com](mailto:535145966@qq.com)

>> 您好可以给我发一份吗 1367955240@qq.com

**Comment by ming-asm** [comment]
没有(>﹏<)发自我的华为手机-------- 原始邮件 --------发件人： 范斌 <notifications@github.com>日期： 2020年8月23日周日 11:03收件人： Danbinabo/insighrface <insighrface@noreply.github.com>抄送： ming-asm <19120318@bjtu.edu.cn>, Comment <comment@noreply.github.com>主    题： Re: [Danbinabo/insighrface] No module named 'FaceRecognizer' (#8)



作者你好，最近我也在学习insightface，您的项目很好，已Star，我在尝试运行运行你的2_demo.py时，import FaceRecognizer时出现No module named 'FaceRecognizer'错误，也没有找到FaceRecognizer.py文件。请问时文件缺失了吗。

请问作者发给你了吗？能不能发给我一份呢？邮箱[1360090837@qq.com](mailto:1360090837@qq.com
请问作者发你了吗？能不能也发我一份？谢谢啦～邮箱535145966@qq.com




您好,请问可以给我发一份吗1367955240@qqcom

**Comment by YuDeng321** [comment]
以Star 同球 820017785@qq.com

**Comment by 623416947** [comment]
it's in the readme.md file.
